Groups:
    ExampleGroupName:
        Time: 1-Hour
        # Moves players to the group 'ExampleGroupName' 
        # after 1 hour of playing unless their group inherits from it

Items:
    326:
        Time: 3-Hours
        Name: Water Bucket
        # You have to use item ID, Name is what is displayed to the player when they unlock it.
    259:
        Time: 1-Day
        Name: Flint and Steel
    327:
        Time: 3-Days
        Name: Lava Bucket

WriteDelay: 10-Minutes
        # Only save file to disk every 10 minutes